import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/providers";
import DesktopNavigation from "@/components/desktop-navigation";
import TopBar from "@/components/top-bar";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="flex">
            <DesktopNavigation />
            <div className=" md:ml-60 w-full md:px-8 py-4">
              {/* <MobileNavigation /> */}
              <TopBar />
              <main className="flex px-8 max-w-7xl mt-4 w-full container mx-auto">
                {children}
                <Toaster />
              </main>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
